# Change these first
owner: mo-maher # Your GitHub organization or username, where this repository lives
repo: my-upptime # The name of this repository

sites:
  - name: Ruoaa Magazine
    url: https://ruoaa.com
  - name: Slow endpoint
    url: https://ruoaa.com
    maxResponseTime: 2000
  - name: Google
    url: https://www.google.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /my-upptime
  logoUrl: https://www.ruoaa.com/wp-content/uploads/2022/06/cropped-ruoaa-logo.webp
  name: Ruoaa Uptime
  introTitle: "**ٌRuoaa Magazine** status monitor"
  introMessage: This is a status page which uses **real-time** data about our [Ruoaa Magazine](https:ruoaa.com).
  theme: ocean
  i18n:
    activeIncidents: الأحداث النشطة
    allSystemsOperational: كل الأنظمة تعمل
  navbar:
    - title: Status
      href: /
    - title: ruoaa Magazine
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
